core/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.home,)
]

mamar_bank/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('accounts.urls')),
    path('transaction/' , include('transactions.urls')),
    path('', HomeView.as_view(),name='home'),
]

transactions/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('Deposit/',views.DepositMoneyView.as_view(),name='deposit'),
    path('withdrow/',views.WithdrowNow.as_view(),name='withdrow'),
    path('transaction_report/',views.TransactionReportView.as_view(),name='report'),
    path('Loan/',views.LoanRequestNow.as_view(),name='loan'),
    path('LoanView/',views.ListLoanView.as_view(),name='list'),
    path('payloan<int:loan_id>/',views.PayLoanView.as_view(),name='pay'),
    path('Treansfer/',views.TransferView.as_view(),name='transfer'),
]

transactions/models.py
from django.db import models
from .constants import TRANSACTION_TYPE
# Create your models here.
from accounts.models import UserBankAccount

class UserTranscation(models.Model):
    account = models.ForeignKey(UserBankAccount,on_delete = models.CASCADE,related_name = 'transactions')
    amount = models.DecimalField(max_digits=12,decimal_places = 2)
    balance_after_transaction = models.DecimalField(max_digits=12,decimal_places = 2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE)
    load_approve = models.BooleanField(default = False)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']




class TransferManey(models.Model):
    sender_account = models.ForeignKey(UserBankAccount, on_delete=models.CASCADE, related_name='sender')
    receiver_account = models.ForeignKey(UserBankAccount, on_delete=models.CASCADE, related_name='receiver')
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    

transactions/forms.py
# from django import forms
# from .models import UserTranscation


# class TransationForm(forms.ModelForm):
#     class Meta:
#         model = UserTranscation
#         fields = ["amount", "transaction_type"]

#     def __init__(self, *args, **kwargs):
#         self.user_account = kwargs.pop('account')
#         super().__init__(*args, **kwargs)
#         self.fields["transaction_type"].disabled = True
#         self.fields["transaction_type"].widget = forms.HiddenInput()

# class DepositeForm(TransationForm):
#     def clean_amount(self):
#         min_amount = 100
#         amount = self.cleaned_data.get("amount")
#         if amount < min_amount:
#             raise forms.ValidationError(f"You need to deposite at least {min_amount}$")
#         return amount


# class WithdrawForm(TransationForm):

#     def clean_amount(self):
#         account = self.account
#         min_withdraw_amount = 500
#         max_withdraw_amount = 20000
#         balance = account.balance # 1000
#         amount = self.cleaned_data.get('amount')
#         if amount < min_withdraw_amount:
#             raise forms.ValidationError(
#                 f'You can withdraw at least {min_withdraw_amount} $'
#             )

#         if amount > max_withdraw_amount:
#             raise forms.ValidationError(
#                 f'You can withdraw at most {max_withdraw_amount} $'
#             )

#         if amount > balance: # amount = 5000, tar balance ache 200
#             raise forms.ValidationError(
#                 f'You have {balance} $ in your account. '
#                 'You can not withdraw more than your account balance'
#             )

#         return amount

# class loanReguest(TransationForm):
#     def clean_amount(self):
#         amount = self.cleaned_data.get("amount")
#         return amount



from django import forms
from .models import UserTranscation,TransferManey
class TransactionForm(forms.ModelForm):
    class Meta:
        model = UserTranscation
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account') # account value ke pop kore anlam
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True # ei field disable thakbe
        self.fields['transaction_type'].widget = forms.HiddenInput() # user er theke hide kora thakbe

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):
    def clean_amount(self): # amount field ke filter korbo
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount') # user er fill up kora form theke amra amount field er value ke niye aslam, 50
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount


class WithdrawForm(TransactionForm):

    def clean_amount(self):
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance # 1000
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )

        if amount > balance: # amount = 5000, tar balance ache 200
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount



class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        return amount
    



class TransferForm(forms.ModelForm):
    class Meta:
        model = TransferManey
        fields = ['receiver_account', 'amount', 'sender_account']

transactions/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from .models import UserTranscation

# Create your views here.
from django.views.generic import CreateView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .constants import WITHDRAWAL, DEPOSIT, LOAN, LOAN_PAID
from .forms import DepositForm, WithdrawForm, LoanRequestForm, TransferForm
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.core.mail import EmailMessage ,EmailMultiAlternatives
class TranscationCreateMixins(LoginRequiredMixin, CreateView):

    template_name = "transaction.html"
    title = ""
    model = UserTranscation
    success_url = reverse_lazy("report")

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs.update(
            {
                "account": self.request.user.account,
            }
        )
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"title": self.title})

        return context


def send_transfer_email(user,subject ,amount,template):
    message = render_to_string(template, {
            'user': user,
            'amount': amount,
        })
    send_mail = EmailMultiAlternatives(subject, "", to=[user.email])
    send_mail.attach_alternative(message,'text/html')
    send_mail.send()

# class DepositeNow(TranscationCreateMixins):
#     form_class = DepositeForm
#     title = "Deposit"

#     def get_initial(self):
#         initial = {'transaction_type':DEPOSIT}
#         return initial


#     def form_valid(self,form):
#         amount = form.cleaned_data.get('amount')
#         account = self.request.user.account
#         account.balance += amount
#         account.save(
#             update_fields = ['balance']
#         )
#         messages.success(self.request,'{amount}$ was deposite amount add sccussfully ')
#         return super().form_valid(form)


class DepositMoneyView(TranscationCreateMixins):
    form_class = DepositForm
    title = "Deposit Form"

    def get_initial(self):
        initial = {"transaction_type": DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get("amount")
        account = self.request.user.account
        transaction = form.save(commit=False)

        transaction.account = account
        transaction.balance_after_transaction = account.balance + amount
        transaction.save()

        account.balance += amount
        account.save(update_fields=["balance"])

        messages.success(
            self.request,
            f'{"{:,.2f}".format(float(amount))}$ was deposited to your account successfully',
        )
        send_transfer_email(self.request.user,amount,'Deposit Maney ','d.html')
        return super().form_valid(form)


class WithdrowNow(TranscationCreateMixins):
    form_class = WithdrawForm
    title = "Withdraw"

    def get_initial(self):
        initial = {"transaction_type": WITHDRAWAL}
        return initial

    def get_form_kwargs(self, **kwargs):
        form_kwargs = super().get_form_kwargs(**kwargs)
        form_kwargs["account"] = self.request.user.account
        return form_kwargs

    def form_valid(self, form):
        amount = form.cleaned_data.get("amount")
        account = self.request.user.account
        transaction = form.save(commit=False)
        transaction.account = account
        transaction.balance_after_transaction = account.balance - amount
        transaction.save()
        account.balance -= amount
        account.save(update_fields=["balance"])
        messages.success(self.request, f"{amount}$ was withdrawn successfully")
        send_transfer_email(self.request.user,'Withdrowal Now',amount,'d.html')
        return super().form_valid(form)


class LoanRequestNow(TranscationCreateMixins):
    form_class = LoanRequestForm
    title = "Request of Loan"

    def get_initial(self):
        initail = {"transaction_type": LOAN}
        return initail

    def form_valid(self, form):
        amount = form.cleaned_data.get("amount")

        current_loan = UserTranscation.objects.filter(
            account=self.request.user.account, transaction_type=3, load_approve=True
        ).count()

        if current_loan >= 3:
            return HttpResponse("Sir Your Loan limited already cross")
        messages.success(self.request, "loan submitted successfully")
        send_transfer_email(self.request.user,'Loan Request',amount,'lon.html')
        return super().form_valid(form)


class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = "transaction_report.html"
    model = UserTranscation
    balance = 0

    def get_queryset(self):
        queryset = super().get_queryset().filter(account=self.request.user.account)

        start_date_str = self.request.GET.get("start_date")
        end_date_str = self.request.GET.get("end_data")

        if start_date_str and end_date_str:
            statr_date = datetime.strptime(start_date_str, "%Y-%m-%d").date()
            end_date = datetime.strptime(end_date_str, "%Y-%m-%d").date()

            queryset = UserTranscation.objects.filter(
                timestamp_date_gte=statr_date, timestamp_date_lte=end_date
            )

            self.balance = UserTranscation.objects.filter(
                timestamp_date_gte=statr_date, timestamp_date_lte=end_date
            ).aaggregate(Sum("amount"))["amount__sum"]
        else:
            self.balance = self.request.user.account.balance
        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"account": self.request.user.account})
        return context


class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(UserTranscation, id=loan_id)
        print(loan)
        if loan.loan_approve:
            user_account = loan.account
            # Reduce the loan amount from the user's balance
            # 5000, 500 + 5000 = 5500
            # balance = 3000, loan = 5000
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.loan_approved = True
                loan.transaction_type = LOAN_PAID
                loan.save()
                return redirect("list")
            else:
                messages.error(
                    self.request, f"Loan amount is greater than available balance"
                )

        return redirect("loan")


class ListLoanView(LoginRequiredMixin, ListView):
    model = UserTranscation
    template_name = "loan.html"
    context_object_name = "loans"

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = UserTranscation.objects.filter(
            account=user_account, transaction_type=LOAN
        )
        return queryset


class TransferView(LoginRequiredMixin, CreateView):
    template_name = "transfer.html"
    success_url = reverse_lazy('report')
    form_class = TransferForm

    def form_valid(self, form):
        sender_user = form.cleaned_data["sender_account"]
        receiver_user = form.cleaned_data["receiver_account"]
        amount = form.cleaned_data["amount"]

        if sender_user.balance >= amount:
            sender_user.balance -= amount
            receiver_user.balance += amount
            sender_user.save()
            messages.success(self.request,'Money Transfer Successfully !')
            send_transfer_email(self.request.user,'Transfer Maney',amount,'ts.html')
            receiver_user.save()
            return super().form_valid(form)
        else:
            form.add_error("amount", "Insufficient funds")
            return super().form_invalid(form)

transactions/templates/app.html
<p> Welcome {{user.first_name}} in Mamar Bank </P>
<h1>Congration You Appoved </h1>
<p> You are  Current Balance Now {{user.account.balance}}</p>
<p>Mamar Bank Ltd.............</p>

transactions/templates/d.html
<p> Welcome {{user.first_name}} in Mamar Bank </P>
<p> You are deposite {{amount}}</p>
<p>Congrations Your Deposite Successfully and Current Balance Now {{user.account.balance}}</p>
<p>Mamar Bank Ltd.............</p>

transactions/templates/loan.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block content %}
<div class="my-5 py-3 px-4 w-50 m-auto shadow rounded ">
  <h1 class="fw-bold  text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border "
  >
    <thead class=" text-white text-left">
      <tr
        class="bg-success rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 fw-bold "
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2 text-danger fw-bold text-danger">
          {{ loan.load_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.load_approve %}
          <a class="fw-bold text-decoration-none px-4 py-2 rounded-lg" href="{% url 'pay' loan.id %}">Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

transactions/templates/lon.html
<p> Welcome {{user.first_name}} in Mamar Bank </P>
    <p> You are Loan {{amount}}</p>
    <p>Congrations Your Deposite Successfully and Current Balance Now {{user.account.balance}}</p>
    <p>Mamar Bank Ltd.............</p>

transactions/templates/transaction.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %}
{% block content %}

<div class=" w-100 d-flex justify-content-center  mt-5">
    <div class="shadow w-50  rounded">
        {% if title == 'Request of Loan' %}
        <div><a class="ms-4 mt-4 text-decoration-none text-dark fw-bold" href="{%url 'list'%}">View All Loan
            List</a></div>
        {% endif %}

        <h1 class="font-bold fs-1 text-center pb-5 pt-10 px-5">
            {{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label style="margin-left: 40%;" class=" fw-bolder mb-4" for="amount">
                    Amount
                </label>
                <input class="shadow form-control m-auto w-50" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <button style="margin-left:30%;"
                    class="btn btn-success px-5"
                    type="submit">
                    Submit
                </button>
        </form>
    </div>

</div>
{% endblock %}

transactions/templates/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% block head_title %} Transaction Report{% endblock %} {% block content %}


<div class="mb-5 ">
  <h1 class="fw-bold fs-1 text-center  pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'report' %}">
    <div class="d-flex justify-content-center">
      <div
        class="mb-5  px-2  border rounded  d-flex justify-content-between align-items-center  p-3 shadow-sm mx-3"
      >
        <label for="start_date">From:</label>
        <input style="outline: none; border: none; width: 70%;"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mb-5  px-2  border rounded  d-flex justify-content-between align-items-center  p-3 shadow-sm mx-3"
      >
        <label for="end_date">To:</label>
        <input
        style="outline: none; border: none; width: 70%;"
          type="date"
          id="start_date"
          name="start_date"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="btn  p-3 btn-success text-light"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-75 shadow rounded px-5  mt-5 "
  >
    <thead class="bg-success text-white text-left">
      <tr
        class=" rounded p-5  text-light fw-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 fw-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-danger fw-bold{% else %} text-success  {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction}}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-primary text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

transactions/templates/transfer.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}
{% block content %}
<div  class='mt-5  mb-5  m-auto shadow w-50'>
  <form method="post" class='w-50  m-auto  mt-5 mb-5 '>
    <h2>Transfer Money</h2>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success px-5 mb-5" type="submit">Transfer</button>
  </form>
</div>
{% endblock %}

transactions/templates/ts.html
<p>Welcome {{user.first_name}} in Mamar Bank</p>
<p>Congrations Dear Customer</p>
<p>Your Account Maney Transfer Succussfully !</P>
<p>Mamar Bank Ltd.............</p>